// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function Search(arg1) {
    return window['go']['main']['App']['Search'](arg1);
}

export function GetIndexStatus() {
    return window['go']['main']['App']['GetIndexStatus']();
}

export function PauseIndexing() {
    return window['go']['main']['App']['PauseIndexing']();
}

export function ResumeIndexing() {
    return window['go']['main']['App']['ResumeIndexing']();
}

export function ReindexNow() {
    return window['go']['main']['App']['ReindexNow']();
}

export function AddFolder(arg1) {
    return window['go']['main']['App']['AddFolder'](arg1);
}

export function GetFolders() {
    return window['go']['main']['App']['GetFolders']();
}

export function OpenFile(arg1) {
    return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
    return window['go']['main']['App']['OpenFolder'](arg1);
}

export function GetPreviewClipPath(arg1, arg2) {
    return window['go']['main']['App']['GetPreviewClipPath'](arg1, arg2);
}
