// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SearchResultDTO {
    filePath: string;
    fileName: string;
    fileType: string;
    extension: string;
    sizeBytes: number;
    thumbnailPath: string;
    startTime: number;
    endTime: number;
}

export interface IndexStatusDTO {
    totalFiles: number;
    indexedFiles: number;
    currentFile: string;
    isRunning: boolean;
}

export function Search(query: string): Promise<SearchResultDTO[]>;
export function GetIndexStatus(): Promise<IndexStatusDTO>;
export function PauseIndexing(): Promise<void>;
export function ResumeIndexing(): Promise<void>;
export function ReindexNow(): Promise<void>;
export function AddFolder(path: string): Promise<void>;
export function GetFolders(): Promise<string[]>;
export function OpenFile(path: string): Promise<void>;
export function OpenFolder(path: string): Promise<void>;
export function GetPreviewClipPath(videoPath: string, timestamp: number): Promise<string>;
